# Copyright 2014 MERCIER David
# Be careful to put a comma + a space between each data...! (YAML convention)
#################################################################################
# Absolute path to your nanoindentation results (optional)
# Uncomment to activate...
data_path: ./Data_indentation